services:
#    test_locations.example:
#        class: Test\LocationsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    locations.data_provider:
        class: \Test\LocationsBundle\Service\DataProviderService
        arguments: ["@file_locator", "@validator"]