services:
#    test_locations.example:
#        class: Test\LocationsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    locations.data_provider:
        class: \Test\LocationsBundle\Service\DataProviderService
        arguments: ["@validator", "@serializer"]


#        "symfony/symfony": "3.4",
#        "guzzlehttp/guzzle": "^6.2@dev",
#        "jms/serializer": "^1.10@dev",
#        "justblackbird/jms-serializer-strict-json": "dev-master"